### ISSUE TITLE
didn't work  when i use lodash-es

### ISSUE THREAD

**Issue by u373693041** [molgenis/vite-plugin-inline#20]
VM16:77  Uncaught SyntaxError: Unexpected token 'export'
    at Or (index.html:12:5088)
    at index.html:12:5169
    at NodeList.forEach (<anonymous>)
    at index.html:12:5158
    at index.html:12:5233

**Comment by dennishendriksen** [comment]
Hello @u373693041,

Apologies for the late reply. I am not familiar with lodash-es. Could you tell me how to reproduce this issue?

Best regards,
@dennishendriksen
